### ISSUE TITLE
Specify adafruit_imageload dependencies

### ISSUE THREAD

**Issue by wormyrocks** [notnavindu/adafruit-macropad-hotkeys-with-extensions#1]
This project inherits the adafruit_imageload dependency from the [bongo](https://github.com/christanaka/circuitpython-bongo) repo, but doesn't mention it in README.
I'm not sure what best practices are for Adafruit package managed stuff, but it might be good either to include adafruit_imageload in `/lib`, or at least to link back to the [installation instructions for circuitpython-bongo](https://github.com/christanaka/circuitpython-bongo#quick-start) that resolve the dependency.

Cheers, I hope to contribute to this soon. Pomodoro timers are useful.

**Comment by notnavindu** [comment]
Thanks for catching that @wormyrocks. I added the `adafruit_imageload` library to `/lib` 🍻
